import {
  User,
  Project,
  ProjectMember,
  Task,
  Milestone,
  TimeLog,
  Invoice,
  Contract,
  DevContractProfile,
  DevRateConfig,
} from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_super_admin',
    name: 'Sarah Dubois',
    email: 'sarah.dubois@intranet.corp',
    role: 'SUPER_ADMIN',
    job_title: 'Directrice Générale & Super-Administrateur',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-01-10T09:00:00Z',
  },
  {
    id: 'usr_pm_1',
    name: 'Alexandre Mercier',
    email: 'alexandre.mercier@intranet.corp',
    role: 'PROJECT_MANAGER',
    job_title: 'Gestionnaire des Projets / Lead Scrum & Delivery',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-01-12T09:30:00Z',
  },
  {
    id: 'usr_dev_1',
    name: 'Marc Laurent',
    email: 'marc.laurent@intranet.corp',
    role: 'DEV',
    job_title: 'Lead Fullstack Developer (React/Node) - Prestataire Forfait',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-01-15T10:30:00Z',
  },
  {
    id: 'usr_dev_2',
    name: 'Lucas Martin',
    email: 'lucas.martin@intranet.corp',
    role: 'DEV',
    job_title: 'Senior Backend & DevOps Engineer - Prestataire Forfait',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-02-01T08:45:00Z',
  },
  {
    id: 'usr_dev_3',
    name: 'Camille Rousseau',
    email: 'camille.rousseau@intranet.corp',
    role: 'DEV',
    job_title: 'Frontend UI/UX Specialist - Prestataire Forfait',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-02-15T14:20:00Z',
  },
  {
    id: 'usr_client_1',
    name: 'Élodie Bernard',
    email: 'elodie.bernard@acme-retail.fr',
    role: 'CLIENT',
    job_title: 'Directrice E-Commerce & Omnicanal (Acme Retail)',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-02-20T11:00:00Z',
  },
  {
    id: 'usr_client_2',
    name: 'Thomas Leroy',
    email: 'thomas.leroy@fintech-horizon.com',
    role: 'CLIENT',
    job_title: 'Directeur Produit & Partenariats (FinTech Horizon)',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-03-01T16:00:00Z',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'prj_1',
    name: 'Refonte E-Commerce NextGen',
    description: 'Modernisation de la boutique en ligne avec catalogue unifié, panier temps réel et intégration ERP.',
    client_id: 'usr_client_1',
    manager_id: 'usr_pm_1',
    status: 'EN_COURS',
    progress_percent: 68,
    deadline: '2026-10-15',
    created_at: '2026-04-01T08:00:00Z',
    budget: 65000,
    category: 'Web & E-Commerce',
  },
  {
    id: 'prj_2',
    name: 'Application Mobile B2B & Scan QR',
    description: 'Application mobile terrain pour les commerciaux et clients grossistes avec commande en mode déconnecté.',
    client_id: 'usr_client_1',
    manager_id: 'usr_pm_1',
    status: 'RECETTE',
    progress_percent: 85,
    deadline: '2026-09-30',
    created_at: '2026-03-15T09:00:00Z',
    budget: 48000,
    category: 'Mobile iOS / Android',
  },
  {
    id: 'prj_3',
    name: 'Portail Paiement Sécurisé & Intégration Bancaire',
    description: 'Passerelle de paiement PCI-DSS avec réconciliation automatique et gestion des flux multi-devises.',
    client_id: 'usr_client_2',
    manager_id: 'usr_pm_1',
    status: 'EN_COURS',
    progress_percent: 42,
    deadline: '2026-11-20',
    created_at: '2026-05-10T10:00:00Z',
    budget: 82000,
    category: 'Fintech & Sécurité',
  },
  {
    id: 'prj_4',
    name: 'Audit Architecture & Migration Cloud GCP',
    description: 'Audit de scalabilité et migration de 12 microservices vers Cloud Run et Cloud SQL.',
    client_id: 'usr_client_2',
    manager_id: 'usr_super_admin',
    status: 'A_VENIR',
    progress_percent: 15,
    deadline: '2026-12-15',
    created_at: '2026-06-01T11:00:00Z',
    budget: 34000,
    category: 'Infrastructure Cloud',
  },
];

export const INITIAL_PROJECT_MEMBERS: ProjectMember[] = [
  // Project 1 members: Marc, Camille
  { id: 'pm_1', project_id: 'prj_1', user_id: 'usr_dev_1' },
  { id: 'pm_2', project_id: 'prj_1', user_id: 'usr_dev_3' },
  // Project 2 members: Marc, Lucas
  { id: 'pm_3', project_id: 'prj_2', user_id: 'usr_dev_1' },
  { id: 'pm_4', project_id: 'prj_2', user_id: 'usr_dev_2' },
  // Project 3 members: Lucas, Marc
  { id: 'pm_5', project_id: 'prj_3', user_id: 'usr_dev_2' },
  { id: 'pm_6', project_id: 'prj_3', user_id: 'usr_dev_1' },
  // Project 4 members: Lucas
  { id: 'pm_7', project_id: 'prj_4', user_id: 'usr_dev_2' },
];

export const INITIAL_TASKS: Task[] = [
  // Tasks for Project 1: Refonte E-Commerce
  {
    id: 'tsk_101',
    project_id: 'prj_1',
    title: 'Intégration du nouveau tunnel de commande responsive',
    description: 'Implémenter le stepper de checkout en 3 étapes avec validation des adresses et calcul frais de port.',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    is_client_visible: true,
    created_by: 'usr_dev_1',
    assigned_to: 'usr_dev_3',
    logged_hours: 14.5,
    due_date: '2026-09-12',
    created_at: '2026-08-20T09:00:00Z',
    comments: [
      {
        id: 'cmt_1',
        task_id: 'tsk_101',
        user_id: 'usr_dev_1',
        user_name: 'Marc Laurent',
        user_role: 'DEV',
        content: 'Faire attention au debounce sur la vérification automatique du code postal.',
        is_internal: true,
        created_at: '2026-08-22T11:15:00Z',
      },
    ],
  },
  {
    id: 'tsk_102',
    project_id: 'prj_1',
    title: 'Optimisation de la mise en cache Redis & Varnish',
    description: 'Configuration du cache TTL sur les fiches produits et invalidation automatique via webhook ERP.',
    status: 'DONE',
    priority: 'MEDIUM',
    is_client_visible: false, // INTERNE
    created_by: 'usr_dev_1',
    assigned_to: 'usr_dev_1',
    logged_hours: 9,
    due_date: '2026-08-28',
    created_at: '2026-08-15T14:00:00Z',
    comments: [
      {
        id: 'cmt_2',
        task_id: 'tsk_102',
        user_id: 'usr_dev_1',
        user_name: 'Marc Laurent',
        user_role: 'DEV',
        content: 'Temps de réponse TTFB passé de 420ms à 48ms sur le cluster de dev.',
        is_internal: true,
        created_at: '2026-08-27T16:00:00Z',
      },
    ],
  },
  {
    id: 'tsk_103',
    project_id: 'prj_1',
    title: 'Module de filtres multicritères et recherche Algolia',
    description: 'Facettes dynamiques (taille, couleur, prix, disponibilité magasin) avec auto-complétion instantanée.',
    status: 'REVIEW',
    priority: 'HIGH',
    is_client_visible: true,
    created_by: 'usr_dev_3',
    assigned_to: 'usr_dev_3',
    logged_hours: 18,
    due_date: '2026-09-08',
    created_at: '2026-08-18T10:00:00Z',
    comments: [],
  },
  {
    id: 'tsk_104',
    project_id: 'prj_1',
    title: 'Connecteur Webhook pour synchronisation stock SAP',
    description: 'Script de synchronisation delta toutes les 10 minutes avec gestion des reprises sur erreur et alertes Slack.',
    status: 'TODO',
    priority: 'MEDIUM',
    is_client_visible: false, // INTERNE
    created_by: 'usr_admin_1',
    assigned_to: 'usr_dev_1',
    logged_hours: 0,
    due_date: '2026-09-20',
    created_at: '2026-08-25T11:00:00Z',
    comments: [],
  },
  {
    id: 'tsk_105',
    project_id: 'prj_1',
    title: 'Mise en conformité RGPD & Gestionnaire de cookies Axeptio',
    description: 'Installation de la bannière de consentement et traçabilité des refus selon directives CNIL.',
    status: 'DONE',
    priority: 'LOW',
    is_client_visible: true,
    created_by: 'usr_admin_1',
    assigned_to: 'usr_dev_3',
    logged_hours: 6,
    due_date: '2026-08-24',
    created_at: '2026-08-10T10:00:00Z',
    comments: [],
  },

  // Tasks for Project 2: App Mobile B2B
  {
    id: 'tsk_201',
    project_id: 'prj_2',
    title: 'Scan de code-barres et QR code hors-ligne',
    description: 'Intégration du SDK de capture caméra avec base SQLite locale pour scan rapide des références magasin.',
    status: 'REVIEW',
    priority: 'HIGH',
    is_client_visible: true,
    created_by: 'usr_dev_2',
    assigned_to: 'usr_dev_2',
    logged_hours: 22,
    due_date: '2026-09-05',
    created_at: '2026-08-12T09:30:00Z',
    comments: [],
  },
  {
    id: 'tsk_202',
    project_id: 'prj_2',
    title: 'Synchronisation bidirectionnelle des commandes en tâche de fond',
    description: 'Service de réessai exponentiel dès que la connectivité réseau 4G/Wifi est rétablie.',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    is_client_visible: false, // INTERNE
    created_by: 'usr_dev_2',
    assigned_to: 'usr_dev_2',
    logged_hours: 16,
    due_date: '2026-09-15',
    created_at: '2026-08-16T15:00:00Z',
    comments: [],
  },
  {
    id: 'tsk_203',
    project_id: 'prj_2',
    title: 'Validation des maquettes d’export PDF de devis',
    description: 'Génération côté client des fiches récapitulatives avec signature numérique manuelle sur écran tactile.',
    status: 'DONE',
    priority: 'MEDIUM',
    is_client_visible: true,
    created_by: 'usr_dev_1',
    assigned_to: 'usr_dev_1',
    logged_hours: 11,
    due_date: '2026-08-30',
    created_at: '2026-08-05T13:00:00Z',
    comments: [],
  },

  // Tasks for Project 3: Portail Paiement
  {
    id: 'tsk_301',
    project_id: 'prj_3',
    title: 'Intégration du protocole 3D-Secure v2.2',
    description: 'Gestion du frictionless flow et des challenges biométriques conformes DSP2.',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    is_client_visible: true,
    created_by: 'usr_dev_2',
    assigned_to: 'usr_dev_2',
    logged_hours: 26,
    due_date: '2026-09-28',
    created_at: '2026-08-01T08:00:00Z',
    comments: [],
  },
  {
    id: 'tsk_302',
    project_id: 'prj_3',
    title: 'Chiffrement AES-256 des tokens bancaires au repos',
    description: 'Stockage sécurisé avec rotation mensuelle des clés via Google Cloud KMS.',
    status: 'TODO',
    priority: 'HIGH',
    is_client_visible: false, // INTERNE
    created_by: 'usr_dev_2',
    assigned_to: 'usr_dev_2',
    logged_hours: 0,
    due_date: '2026-10-10',
    created_at: '2026-08-20T10:00:00Z',
    comments: [],
  },
  {
    id: 'tsk_303',
    project_id: 'prj_3',
    title: 'Tableau de bord de réconciliation des virements SEPA',
    description: 'Interface de suivi pour l’équipe comptabilité avec filtre par statut de compensation.',
    status: 'TODO',
    priority: 'MEDIUM',
    is_client_visible: true,
    created_by: 'usr_dev_1',
    assigned_to: 'usr_dev_1',
    logged_hours: 4,
    due_date: '2026-10-25',
    created_at: '2026-08-22T09:00:00Z',
    comments: [],
  },
];

export const INITIAL_MILESTONES: Milestone[] = [
  // Milestones for Project 1: Refonte E-Commerce
  {
    id: 'mls_101',
    project_id: 'prj_1',
    title: 'Jalon 1 : Spécifications & Validation du Design System',
    description: 'Livraison de la charte graphique Figma, des composants UI responsive et du cahier des charges fonctionnel.',
    due_date: '2026-05-15',
    status: 'VALIDATED',
    client_feedback: 'Design validé par le comité de direction. Excellente ergonomie sur mobile.',
    feedback_date: '2026-05-18T14:30:00Z',
    deliverable_url: 'https://figma.com/design-system-spec-acme',
    deliverable_tag: 'Design & UX',
  },
  {
    id: 'mls_102',
    project_id: 'prj_1',
    title: 'Jalon 2 : Version Bêta du Catalogue & Moteur de Recherche',
    description: 'Mise en ligne sur l’environnement de pré-production avec 5 000 références et recherche Algolia.',
    due_date: '2026-08-30',
    status: 'PENDING',
    client_feedback: undefined,
    deliverable_url: 'https://staging.acme-retail-next.dev/catalogue',
    deliverable_tag: 'Livraison Recette',
  },
  {
    id: 'mls_103',
    project_id: 'prj_1',
    title: 'Jalon 3 : Tunnel d’Achat & Passerelle de Paiement',
    description: 'Intégration complète du checkout, calcul TVA international et validation des flux CB/PayPal.',
    due_date: '2026-09-25',
    status: 'PENDING',
    deliverable_url: 'https://staging.acme-retail-next.dev/checkout',
    deliverable_tag: 'Tunnel de Vente',
  },
  {
    id: 'mls_104',
    project_id: 'prj_1',
    title: 'Jalon 4 : Mise en Production & Bascule DNS',
    description: 'Déploiement final, monitoring Datadog, bascule DNS sans interruption et tests de charge.',
    due_date: '2026-10-15',
    status: 'PENDING',
    deliverable_tag: 'Production',
  },

  // Milestones for Project 2: App Mobile B2B
  {
    id: 'mls_201',
    project_id: 'prj_2',
    title: 'Jalon 1 : Prototype Interactif iOS & Android',
    description: 'Validation de l’expérience utilisateur sur smartphones et tablettes des commerciaux.',
    due_date: '2026-05-30',
    status: 'VALIDATED',
    client_feedback: 'Parcours très fluide pour nos équipes terrain.',
    feedback_date: '2026-06-02T10:00:00Z',
    deliverable_url: 'https://testflight.apple.com/join/demo-b2b',
    deliverable_tag: 'Prototype',
  },
  {
    id: 'mls_202',
    project_id: 'prj_2',
    title: 'Jalon 2 : Version TestFlight / APK Bêta avec Mode Offline',
    description: 'Livraison de la version Bêta avec moteur de synchronisation hors-ligne et scan code-barre.',
    due_date: '2026-08-25',
    status: 'CHANGES_REQUESTED',
    client_feedback: 'Le scan de code-barre fonctionne très bien, mais le bouton d’exportation PDF met parfois plus de 5 secondes à générer le document. Merci d’optimiser la vitesse de compilation.',
    feedback_date: '2026-08-28T09:45:00Z',
    deliverable_url: 'https://testflight.apple.com/join/v0.9-b2b',
    deliverable_tag: 'Release Bêta',
  },
  {
    id: 'mls_203',
    project_id: 'prj_2',
    title: 'Jalon 3 : Déploiement App Store & Google Play Entreprise',
    description: 'Publication sur les stores privés MDM de l’entreprise et formation des administrateurs.',
    due_date: '2026-09-30',
    status: 'PENDING',
    deliverable_tag: 'Publication Stores',
  },

  // Milestones for Project 3: Portail Paiement
  {
    id: 'mls_301',
    project_id: 'prj_3',
    title: 'Jalon 1 : Architecture Technique & Dossier de Sécurité PCI-DSS',
    description: 'Revue d’architecture et homologation de conformité réglementaire bancaire.',
    due_date: '2026-07-15',
    status: 'VALIDATED',
    client_feedback: 'Dossier de conformité validé sans réserve par nos auditeurs externes.',
    feedback_date: '2026-07-20T16:00:00Z',
    deliverable_tag: 'Conformité & Audit',
  },
  {
    id: 'mls_302',
    project_id: 'prj_3',
    title: 'Jalon 2 : Environnement Sandbox & API REST Partenaires',
    description: 'Fourniture de la documentation OpenAPI et de la sandbox pour intégration.',
    due_date: '2026-09-10',
    status: 'PENDING',
    deliverable_url: 'https://sandbox.fintech-gateway.io/docs',
    deliverable_tag: 'Sandbox API',
  },
];

export const INITIAL_TIMELOGS: TimeLog[] = [
  {
    id: 'log_1',
    task_id: 'tsk_101',
    project_id: 'prj_1',
    user_id: 'usr_dev_3',
    user_name: 'Camille Rousseau',
    hours: 4.5,
    description: 'Mise en place des formulaires d’adresse et validation Zod.',
    date: '2026-08-28',
    created_at: '2026-08-28T18:00:00Z',
  },
  {
    id: 'log_2',
    task_id: 'tsk_101',
    project_id: 'prj_1',
    user_id: 'usr_dev_3',
    user_name: 'Camille Rousseau',
    hours: 5.0,
    description: 'Intégration du composant de paiement Stripe Elements dans le tunnel.',
    date: '2026-08-29',
    created_at: '2026-08-29T17:30:00Z',
  },
  {
    id: 'log_3',
    task_id: 'tsk_102',
    project_id: 'prj_1',
    user_id: 'usr_dev_1',
    user_name: 'Marc Laurent',
    hours: 6.0,
    description: 'Configuration du clustering Redis et tests de charge avec k6.',
    date: '2026-08-26',
    created_at: '2026-08-26T19:00:00Z',
  },
  {
    id: 'log_4',
    task_id: 'tsk_201',
    project_id: 'prj_2',
    user_id: 'usr_dev_2',
    user_name: 'Lucas Martin',
    hours: 7.5,
    description: 'Débogage du lecteur de code-barre sur terminaux Android durcis Zebra.',
    date: '2026-08-27',
    created_at: '2026-08-27T17:00:00Z',
  },
];

export const INITIAL_DEV_RATES: DevRateConfig[] = [
  {
    user_id: 'usr_dev_1',
    hourly_rate: 65,
    daily_rate: 480,
    iban_masked: 'FR76 •••• •••• •••• 4892',
    legal_status: 'Micro-entreprise (BNC)',
  },
  {
    user_id: 'usr_dev_2',
    hourly_rate: 70,
    daily_rate: 520,
    iban_masked: 'FR76 •••• •••• •••• 9134',
    legal_status: 'SASU Unipersonnelle',
  },
  {
    user_id: 'usr_dev_3',
    hourly_rate: 60,
    daily_rate: 450,
    iban_masked: 'FR76 •••• •••• •••• 1276',
    legal_status: 'Freelance Indépendant',
  },
];

export const INITIAL_CONTRACTS: Contract[] = [
  // Client Master Contract 1
  {
    id: 'ctr_cli_1',
    contract_number: 'CTR-CLI-2026-001',
    title: 'Contrat Cadre de Réalisation & Refonte E-Commerce NextGen',
    type: 'CLIENT_MASTER_CONTRACT',
    project_id: 'prj_1',
    client_id: 'usr_client_1',
    total_amount_ht: 65000,
    tva_rate: 20,
    total_amount_ttc: 78000,
    status: 'ACTIVE_SIGNED',
    start_date: '2026-04-01',
    end_date: '2026-10-31',
    created_at: '2026-03-25T10:00:00Z',
    signatures: [
      {
        user_id: 'usr_super_admin',
        user_name: 'Sarah Dubois',
        user_role: 'SUPER_ADMIN',
        signed_at: '2026-03-28T14:30:00Z',
        signature_type: 'ELECTRONIC_CERT',
        checksum: 'SHA256:7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069',
      },
      {
        user_id: 'usr_client_1',
        user_name: 'Élodie Bernard',
        user_role: 'CLIENT',
        signed_at: '2026-03-29T09:15:00Z',
        signature_type: 'ELECTRONIC_CERT',
        checksum: 'SHA256:4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a',
      },
    ],
    clauses: [
      'Périmètre forfaitaire : architecture technique, refonte frontend React/Tailwind, intégration ERP SAP et catalogue unifié.',
      'Modalités d’échelonnement : 30% d’acompte à la signature, 35% à la livraison du jalon MVP / Tunnel d’achat, 35% au PV de recette finale.',
      'Garantie de parfait achèvement et correction des anomalies bloquantes pendant 60 jours suivant la mise en production.',
      'Cession des droits patrimoniaux de propriété intellectuelle après paiement intégral de toutes les échéances contractuelles.',
    ],
    deliverables_summary: 'Spécifications, code source audité sous GitHub Enterprise, déploiement Cloud GCP, documentation API et formation équipes.',
    tranches: [
      {
        id: 'tra_cli_1_1',
        contract_id: 'ctr_cli_1',
        title: 'Tranche 1 : Acompte de Démarrage & Cadrage Initial',
        description: 'Lancement du projet, ateliers de cadrage UX et validation des spécifications techniques.',
        percentage: 30,
        amount_ht: 19500,
        amount_ttc: 23400,
        trigger_condition: 'À la signature électronique du contrat',
        due_date: '2026-04-15',
        status: 'PAID',
        paid_at: '2026-04-10',
        invoice_id: 'inv_101',
      },
      {
        id: 'tra_cli_1_2',
        contract_id: 'ctr_cli_1',
        title: 'Tranche 2 : Livraison Jalon MVP & Tunnel Checkout',
        description: 'Mise à disposition de l’environnement de pré-production avec catalogue connecté et panier validé.',
        percentage: 35,
        amount_ht: 22750,
        amount_ttc: 27300,
        trigger_condition: 'À la validation du livrable Jalon 1 (MVP E-Commerce)',
        milestone_id: 'mls_1',
        due_date: '2026-09-20',
        status: 'PAYOUT_REQUESTED',
        invoice_id: 'inv_102',
      },
      {
        id: 'tra_cli_1_3',
        contract_id: 'ctr_cli_1',
        title: 'Tranche 3 : Solde Final & Recette de Mise en Production',
        description: 'Signature du procès-verbal de recette finale, bascule DNS et mise en service live.',
        percentage: 35,
        amount_ht: 22750,
        amount_ttc: 27300,
        trigger_condition: 'À la signature du PV de recette définitive (Jalon 3)',
        milestone_id: 'mls_3',
        due_date: '2026-10-31',
        status: 'PENDING',
      },
    ],
  },

  // Client Master Contract 2
  {
    id: 'ctr_cli_2',
    contract_number: 'CTR-CLI-2026-002',
    title: 'Contrat Cadre Développement Application Mobile B2B & Scan QR',
    type: 'CLIENT_MASTER_CONTRACT',
    project_id: 'prj_2',
    client_id: 'usr_client_1',
    total_amount_ht: 48000,
    tva_rate: 20,
    total_amount_ttc: 57600,
    status: 'ACTIVE_SIGNED',
    start_date: '2026-03-15',
    end_date: '2026-09-30',
    created_at: '2026-03-10T11:00:00Z',
    signatures: [
      {
        user_id: 'usr_super_admin',
        user_name: 'Sarah Dubois',
        user_role: 'SUPER_ADMIN',
        signed_at: '2026-03-14T11:00:00Z',
        signature_type: 'ELECTRONIC_CERT',
        checksum: 'SHA256:1a8565a9dae7204ee92bca3e78634648724113245191216da52fa8b3751e8b6f',
      },
      {
        user_id: 'usr_client_1',
        user_name: 'Élodie Bernard',
        user_role: 'CLIENT',
        signed_at: '2026-03-15T08:30:00Z',
        signature_type: 'ELECTRONIC_CERT',
        checksum: 'SHA256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      },
    ],
    clauses: [
      'Prestation forfaitaire d’ingénierie mobile React Native multiplateforme (iOS & Android).',
      'Échelonnement : 40% démarrage, 40% livraison version bêta testable, 20% validation stores et recette terrain.',
      'SLA de réponse critique sous 4 heures ouvrées en phase de déploiement.',
    ],
    deliverables_summary: 'Binaires iOS (.ipa) et Android (.apk), API de synchronisation SQLite offline, tableau de bord analytics.',
    tranches: [
      {
        id: 'tra_cli_2_1',
        contract_id: 'ctr_cli_2',
        title: 'Tranche 1 : Acompte 40% Lancement Projet Mobile',
        description: 'Mise en place de la stack mobile et des connecteurs d’authentification.',
        percentage: 40,
        amount_ht: 19200,
        amount_ttc: 23040,
        trigger_condition: 'À la signature du contrat',
        due_date: '2026-04-20',
        status: 'PAID',
        paid_at: '2026-04-02',
        invoice_id: 'inv_103',
      },
      {
        id: 'tra_cli_2_2',
        contract_id: 'ctr_cli_2',
        title: 'Tranche 2 : Livraison Version RC2 & Recette Mobile',
        description: 'Version stabilisée avec scan offline et synchronisation automatique.',
        percentage: 40,
        amount_ht: 19200,
        amount_ttc: 23040,
        trigger_condition: 'À la mise à disposition de la version RC2 testable (Jalon Mobile 1)',
        milestone_id: 'mls_4',
        due_date: '2026-09-25',
        status: 'PAYOUT_REQUESTED',
        invoice_id: 'inv_104',
      },
      {
        id: 'tra_cli_2_3',
        contract_id: 'ctr_cli_2',
        title: 'Tranche 3 : Solde 20% Déploiement Stores & Formation',
        description: 'Publication sur les MDM d’entreprise et remise de la documentation technique.',
        percentage: 20,
        amount_ht: 9600,
        amount_ttc: 11520,
        trigger_condition: 'À la recette finale et approbation de déploiement',
        due_date: '2026-10-15',
        status: 'PENDING',
      },
    ],
  },

  // Developer Contract 1 - Marc Laurent (Lead Fullstack)
  {
    id: 'ctr_dev_1',
    contract_number: 'CTR-DEV-2026-001',
    title: 'Contrat Forfaitaire de Développement - Lead Backend & Architecture E-Commerce',
    type: 'DEV_SERVICE_CONTRACT',
    project_id: 'prj_1',
    dev_id: 'usr_dev_1',
    total_amount_ht: 18000,
    tva_rate: 0, // Auto-entrepreneur / Franchise ou B2B sous exonération
    total_amount_ttc: 18000,
    status: 'ACTIVE_SIGNED',
    start_date: '2026-04-01',
    end_date: '2026-10-31',
    created_at: '2026-03-26T14:00:00Z',
    signatures: [
      {
        user_id: 'usr_super_admin',
        user_name: 'Sarah Dubois',
        user_role: 'SUPER_ADMIN',
        signed_at: '2026-03-27T10:00:00Z',
        signature_type: 'ELECTRONIC_CERT',
        checksum: 'SHA256:9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
      },
      {
        user_id: 'usr_dev_1',
        user_name: 'Marc Laurent',
        user_role: 'DEV',
        signed_at: '2026-03-27T16:45:00Z',
        signature_type: 'TYPED',
        signature_data: 'Marc LAURENT',
        checksum: 'SHA256:5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
      },
    ],
    clauses: [
      'Engagement de résultat sur les livrables techniques définis au cahier des charges.',
      'Rémunération échelonnée strictement selon l’achèvement et la validation des jalons contractuels.',
      'Clause de stricte confidentialité (NDA) et engagement de non-concurrence durant la prestation.',
      'Code source fourni sous licence exclusive au donneur d’ordre avec tests unitaires couvrant au minimum 80%.',
    ],
    deliverables_summary: 'Architecture Node/Fastify, connecteur SAP ERP, cache Redis distribué et tunnel de paiement PCI-DSS.',
    tranches: [
      {
        id: 'tra_dev_1_1',
        contract_id: 'ctr_dev_1',
        title: 'Tranche 1 : Acompte de Démarrage & Spécifications API',
        description: 'Mise en place de l’architecture microservices et des schémas de base de données.',
        percentage: 30,
        amount_ht: 5400,
        amount_ttc: 5400,
        trigger_condition: 'À la signature du contrat de prestation',
        due_date: '2026-04-15',
        status: 'PAID',
        paid_at: '2026-04-12',
        invoice_id: 'pay_201',
      },
      {
        id: 'tra_dev_1_2',
        contract_id: 'ctr_dev_1',
        title: 'Tranche 2 : Livraison API Core, Redis & Tunnel Checkout',
        description: 'Implémentation complète du panier temps réel, connecteurs ERP et passerelle de paiement.',
        percentage: 40,
        amount_ht: 7200,
        amount_ttc: 7200,
        trigger_condition: 'À la validation technique du Jalon 1 (MVP E-Commerce)',
        milestone_id: 'mls_1',
        due_date: '2026-09-15',
        status: 'PAYOUT_REQUESTED',
        invoice_id: 'pay_202',
      },
      {
        id: 'tra_dev_1_3',
        contract_id: 'ctr_dev_1',
        title: 'Tranche 3 : Recette Finale, Tests de Charge & Clôture',
        description: 'Passage des tests de charge (10k req/s), recette utilisateur et déploiement production.',
        percentage: 30,
        amount_ht: 5400,
        amount_ttc: 5400,
        trigger_condition: 'À la validation de la Recette Finale (Jalon 3)',
        milestone_id: 'mls_3',
        due_date: '2026-10-31',
        status: 'PENDING',
      },
    ],
  },

  // Developer Contract 2 - Lucas Martin (Senior Backend / DevOps)
  {
    id: 'ctr_dev_2',
    contract_number: 'CTR-DEV-2026-002',
    title: 'Contrat Forfaitaire Ingénierie Mobile & Synchronisation Hors-Ligne',
    type: 'DEV_SERVICE_CONTRACT',
    project_id: 'prj_2',
    dev_id: 'usr_dev_2',
    total_amount_ht: 14000,
    tva_rate: 20,
    total_amount_ttc: 16800,
    status: 'ACTIVE_SIGNED',
    start_date: '2026-03-15',
    end_date: '2026-09-30',
    created_at: '2026-03-12T09:00:00Z',
    signatures: [
      {
        user_id: 'usr_super_admin',
        user_name: 'Sarah Dubois',
        user_role: 'SUPER_ADMIN',
        signed_at: '2026-03-14T15:00:00Z',
        signature_type: 'ELECTRONIC_CERT',
        checksum: 'SHA256:d8b2e3e1185f36e84d4fb400a4df75608b688d01198539268f766e4a849aa01a',
      },
      {
        user_id: 'usr_dev_2',
        user_name: 'Lucas Martin',
        user_role: 'DEV',
        signed_at: '2026-03-15T11:20:00Z',
        signature_type: 'DRAWN',
        signature_data: 'Lucas Martin (SASU LM TECH)',
        checksum: 'SHA256:6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b',
      },
    ],
    clauses: [
      'Facturation B2B émise par SASU LM TECH avec application de la TVA à 20%.',
      'Paiement par virement bancaire SEPA à 15 jours suivant le déclenchement de chaque tranche contractuelle.',
      'Support correctif garanti 30 jours après mise à disposition des binaires stores.',
    ],
    deliverables_summary: 'Moteur de réplication offline SQLite/WatermelonDB, compression des flux réseau et scanner QR temps réel.',
    tranches: [
      {
        id: 'tra_dev_2_1',
        contract_id: 'ctr_dev_2',
        title: 'Tranche 1 : Acompte 30% Architecture & Moteur Sync',
        description: 'Cadrage de la base locale et handshake de synchronisation.',
        percentage: 30,
        amount_ht: 4200,
        amount_ttc: 5040,
        trigger_condition: 'À la signature du contrat',
        due_date: '2026-04-10',
        status: 'PAID',
        paid_at: '2026-04-05',
        invoice_id: 'pay_203',
      },
      {
        id: 'tra_dev_2_2',
        contract_id: 'ctr_dev_2',
        title: 'Tranche 2 : Validation Module Scan & Livrable RC2',
        description: 'Intégration du module caméra et tests sur terminaux Android/iOS durcis.',
        percentage: 40,
        amount_ht: 5600,
        amount_ttc: 6720,
        trigger_condition: 'À la validation du livrable Jalon Mobile 1 (RC2)',
        milestone_id: 'mls_4',
        due_date: '2026-09-15',
        status: 'PAYOUT_REQUESTED',
        invoice_id: 'pay_204',
      },
      {
        id: 'tra_dev_2_3',
        contract_id: 'ctr_dev_2',
        title: 'Tranche 3 : Solde 30% Packaging Stores & Recette Terrain',
        description: 'Génération des certificats de production et livraison des builds signés.',
        percentage: 30,
        amount_ht: 4200,
        amount_ttc: 5040,
        trigger_condition: 'À la validation finale par le client',
        due_date: '2026-09-30',
        status: 'PENDING',
      },
    ],
  },

  // Developer Contract 3 - Camille Rousseau (UI/UX Frontend)
  {
    id: 'ctr_dev_3',
    contract_number: 'CTR-DEV-2026-003',
    title: 'Contrat Forfaitaire Intégration UI/UX & Design System E-Commerce',
    type: 'DEV_SERVICE_CONTRACT',
    project_id: 'prj_1',
    dev_id: 'usr_dev_3',
    total_amount_ht: 9500,
    tva_rate: 0,
    total_amount_ttc: 9500,
    status: 'ACTIVE_SIGNED',
    start_date: '2026-04-15',
    end_date: '2026-10-15',
    created_at: '2026-04-10T15:00:00Z',
    signatures: [
      {
        user_id: 'usr_super_admin',
        user_name: 'Sarah Dubois',
        user_role: 'SUPER_ADMIN',
        signed_at: '2026-04-12T10:00:00Z',
        signature_type: 'ELECTRONIC_CERT',
        checksum: 'SHA256:ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d',
      },
      {
        user_id: 'usr_dev_3',
        user_name: 'Camille Rousseau',
        user_role: 'DEV',
        signed_at: '2026-04-13T18:00:00Z',
        signature_type: 'TYPED',
        signature_data: 'Camille Rousseau',
        checksum: 'SHA256:8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4',
      },
    ],
    clauses: [
      'Prestation forfaitaire d’intégration React / Tailwind CSS selon maquettes Figma validées.',
      'Conformité stricte aux normes d’accessibilité WCAG AA (contraste, navigation clavier, lecteurs d’écran).',
      'Paiement en 2 tranches échelonnées (40% après design system, 60% après validation tunnel).',
    ],
    deliverables_summary: 'Composants Storybook documentés, vues catalogue responsives et tunnel de paiement multi-étapes.',
    tranches: [
      {
        id: 'tra_dev_3_1',
        contract_id: 'ctr_dev_3',
        title: 'Tranche 1 : Design System & Pages Catalogue',
        description: 'Bibliothèque de composants UI réutilisables et fiches produits.',
        percentage: 40,
        amount_ht: 3800,
        amount_ttc: 3800,
        trigger_condition: 'À la validation de la librairie de composants UI',
        due_date: '2026-06-30',
        status: 'PAID',
        paid_at: '2026-06-25',
        invoice_id: 'pay_205',
      },
      {
        id: 'tra_dev_3_2',
        contract_id: 'ctr_dev_3',
        title: 'Tranche 2 : Solde Tunnel de Commande & Responsive QA',
        description: 'Intégration du checkout, modales de paiement et tests multi-navigateurs.',
        percentage: 60,
        amount_ht: 5700,
        amount_ttc: 5700,
        trigger_condition: 'À la recette du tunnel d’achat complet',
        milestone_id: 'mls_1',
        due_date: '2026-09-15',
        status: 'PAYOUT_REQUESTED',
        invoice_id: 'pay_206',
      },
    ],
  },
];

export const INITIAL_DEV_PROFILES: DevContractProfile[] = [
  {
    user_id: 'usr_dev_1',
    legal_status: 'Micro-Entreprise (Franchise en base de TVA art. 293 B du CGI)',
    siren_siret: '849 302 119 00024',
    iban_masked: 'FR76 •••• •••• •••• 4892',
    bic: 'BNPAFRPPXXX',
    active_contracts_count: 1,
    total_contracted_amount: 18000,
    total_paid_amount: 5400,
  },
  {
    user_id: 'usr_dev_2',
    legal_status: 'SASU LM TECH (Capital 5 000 € - TVA FR88 849302119)',
    siren_siret: '891 405 823 00018',
    iban_masked: 'FR76 •••• •••• •••• 9104',
    bic: 'SOGEFRPPXXX',
    active_contracts_count: 1,
    total_contracted_amount: 14000,
    total_paid_amount: 4200,
  },
  {
    user_id: 'usr_dev_3',
    legal_status: 'Entreprise Individuelle (BNC / Profession Libérale)',
    siren_siret: '912 847 301 00012',
    iban_masked: 'FR76 •••• •••• •••• 7731',
    bic: 'CMBRFR2SXXX',
    active_contracts_count: 1,
    total_contracted_amount: 9500,
    total_paid_amount: 3800,
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  // Client Invoices linked to contract tranches
  {
    id: 'inv_101',
    invoice_number: 'FAC-2026-0045',
    type: 'CLIENT_INVOICE',
    title: 'Tranche 1 (30%) - Acompte de Démarrage E-Commerce NextGen',
    project_id: 'prj_1',
    contract_id: 'ctr_cli_1',
    tranche_id: 'tra_cli_1_1',
    client_id: 'usr_client_1',
    amount_ht: 19500,
    tva_rate: 20,
    amount_ttc: 23400,
    status: 'PAID',
    issue_date: '2026-04-01',
    due_date: '2026-04-30',
    paid_at: '2026-04-10',
    payment_method: 'VIREMENT_BANCAIRE',
    items: [
      {
        id: 'item_1',
        description: 'Échéance contractuelle Tranche 1 (30%) - Cadrage & Démarrage projet E-Commerce',
        quantity: 1,
        unit_price: 19500,
        total: 19500,
      },
    ],
    notes: 'Règlement reçu par virement bancaire SEPA. Contrat CTR-CLI-2026-001.',
  },
  {
    id: 'inv_102',
    invoice_number: 'FAC-2026-0089',
    type: 'CLIENT_INVOICE',
    title: 'Tranche 2 (35%) - Échéance Jalon 1 (MVP E-Commerce)',
    project_id: 'prj_1',
    contract_id: 'ctr_cli_1',
    tranche_id: 'tra_cli_1_2',
    client_id: 'usr_client_1',
    amount_ht: 22750,
    tva_rate: 20,
    amount_ttc: 27300,
    status: 'PENDING',
    issue_date: '2026-08-20',
    due_date: '2026-09-20',
    items: [
      {
        id: 'item_2',
        description: 'Échéance contractuelle Tranche 2 (35%) - Livraison et validation Jalon MVP & Tunnel Checkout',
        quantity: 1,
        unit_price: 22750,
        total: 22750,
      },
    ],
    notes: 'Paiement attendu selon l’échéancier contractuel signé. Règlements acceptés par virement ou CB.',
  },
  {
    id: 'inv_103',
    invoice_number: 'FAC-2026-0072',
    type: 'CLIENT_INVOICE',
    title: 'Tranche 1 (40%) - Acompte Démarrage App Mobile B2B',
    project_id: 'prj_2',
    contract_id: 'ctr_cli_2',
    tranche_id: 'tra_cli_2_1',
    client_id: 'usr_client_1',
    amount_ht: 19200,
    tva_rate: 20,
    amount_ttc: 23040,
    status: 'PAID',
    issue_date: '2026-03-20',
    due_date: '2026-04-20',
    paid_at: '2026-04-02',
    payment_method: 'CARTE_BANCAIRE',
    items: [
      {
        id: 'item_3',
        description: 'Échéance contractuelle Tranche 1 (40%) - Lancement développement mobile React Native',
        quantity: 1,
        unit_price: 19200,
        total: 19200,
      },
    ],
    notes: 'Règlement sécurisé par carte bancaire professionnelle.',
  },
  {
    id: 'inv_104',
    invoice_number: 'FAC-2026-0105',
    type: 'CLIENT_INVOICE',
    title: 'Tranche 2 (40%) - Livraison Version RC2 Mobile B2B',
    project_id: 'prj_2',
    contract_id: 'ctr_cli_2',
    tranche_id: 'tra_cli_2_2',
    client_id: 'usr_client_1',
    amount_ht: 19200,
    tva_rate: 20,
    amount_ttc: 23040,
    status: 'PENDING',
    issue_date: '2026-08-25',
    due_date: '2026-09-25',
    items: [
      {
        id: 'item_4',
        description: 'Échéance contractuelle Tranche 2 (40%) - Livraison version RC2 avec scan offline',
        quantity: 1,
        unit_price: 19200,
        total: 19200,
      },
    ],
    notes: 'Facture émise suite à la mise à disposition de la version RC2.',
  },

  // Developer Payout Invoices linked to contract tranches
  {
    id: 'pay_201',
    invoice_number: 'HON-2026-041',
    type: 'DEV_PAYOUT',
    title: 'Tranche 1 (30%) Contrat Forfait - Marc Laurent',
    project_id: 'prj_1',
    contract_id: 'ctr_dev_1',
    tranche_id: 'tra_dev_1_1',
    dev_id: 'usr_dev_1',
    amount_ht: 5400.0,
    tva_rate: 0,
    amount_ttc: 5400.0,
    status: 'PAID',
    issue_date: '2026-04-05',
    due_date: '2026-04-20',
    paid_at: '2026-04-12',
    payment_method: 'VIREMENT_BANCAIRE',
    items: [
      {
        id: 'pitem_1',
        description: 'Tranche contractuelle 1 (30%) - Acompte de démarrage & Spécifications techniques API',
        quantity: 1,
        unit_price: 5400.0,
        total: 5400.0,
      },
    ],
    notes: 'Virement SEPA exécuté vers IBAN FR76 •••• 4892 (Marc Laurent).',
  },
  {
    id: 'pay_202',
    invoice_number: 'HON-2026-052',
    type: 'DEV_PAYOUT',
    title: 'Tranche 2 (40%) Contrat Forfait - Marc Laurent',
    project_id: 'prj_1',
    contract_id: 'ctr_dev_1',
    tranche_id: 'tra_dev_1_2',
    dev_id: 'usr_dev_1',
    amount_ht: 7200.0,
    tva_rate: 0,
    amount_ttc: 7200.0,
    status: 'PENDING',
    issue_date: '2026-08-30',
    due_date: '2026-09-15',
    items: [
      {
        id: 'pitem_2',
        description: 'Tranche contractuelle 2 (40%) - Livraison Jalon 1 (MVP E-Commerce, Fastify & Redis)',
        quantity: 1,
        unit_price: 7200.0,
        total: 7200.0,
      },
    ],
    notes: 'Jalon technique validé - En attente d’exécution du virement comptable.',
  },
  {
    id: 'pay_203',
    invoice_number: 'HON-2026-038',
    type: 'DEV_PAYOUT',
    title: 'Tranche 1 (30%) Contrat Forfait Mobile - Lucas Martin (SASU LM TECH)',
    project_id: 'prj_2',
    contract_id: 'ctr_dev_2',
    tranche_id: 'tra_dev_2_1',
    dev_id: 'usr_dev_2',
    amount_ht: 4200.0,
    tva_rate: 20,
    amount_ttc: 5040.0,
    status: 'PAID',
    issue_date: '2026-03-25',
    due_date: '2026-04-10',
    paid_at: '2026-04-05',
    payment_method: 'VIREMENT_BANCAIRE',
    items: [
      {
        id: 'pitem_3',
        description: 'Tranche contractuelle 1 (30%) - Architecture & Moteur Sync SQLite',
        quantity: 1,
        unit_price: 4200,
        total: 4200.0,
      },
    ],
    notes: 'Facture SASU LM TECH acquittée par virement.',
  },
  {
    id: 'pay_204',
    invoice_number: 'HON-2026-055',
    type: 'DEV_PAYOUT',
    title: 'Tranche 2 (40%) Contrat Forfait Mobile - Lucas Martin (SASU LM TECH)',
    project_id: 'prj_2',
    contract_id: 'ctr_dev_2',
    tranche_id: 'tra_dev_2_2',
    dev_id: 'usr_dev_2',
    amount_ht: 5600.0,
    tva_rate: 20,
    amount_ttc: 6720.0,
    status: 'PENDING',
    issue_date: '2026-08-31',
    due_date: '2026-09-15',
    items: [
      {
        id: 'pitem_4',
        description: 'Tranche contractuelle 2 (40%) - Validation Module Scan & Livrable RC2',
        quantity: 1,
        unit_price: 5600,
        total: 5600.0,
      },
    ],
    notes: 'Livrable RC2 soumis - Virement programmé au 15 septembre.',
  },
  {
    id: 'pay_205',
    invoice_number: 'HON-2026-047',
    type: 'DEV_PAYOUT',
    title: 'Tranche 1 (40%) Contrat UI/UX - Camille Rousseau',
    project_id: 'prj_1',
    contract_id: 'ctr_dev_3',
    tranche_id: 'tra_dev_3_1',
    dev_id: 'usr_dev_3',
    amount_ht: 3800.0,
    tva_rate: 0,
    amount_ttc: 3800.0,
    status: 'PAID',
    issue_date: '2026-06-20',
    due_date: '2026-07-05',
    paid_at: '2026-06-25',
    payment_method: 'VIREMENT_BANCAIRE',
    items: [
      {
        id: 'pitem_5',
        description: 'Tranche contractuelle 1 (40%) - Design System & Composants Catalogue validés',
        quantity: 1,
        unit_price: 3800,
        total: 3800.0,
      },
    ],
    notes: 'Virement honoraires effectué.',
  },
  {
    id: 'pay_206',
    invoice_number: 'HON-2026-059',
    type: 'DEV_PAYOUT',
    title: 'Tranche 2 (60%) Contrat UI/UX - Camille Rousseau',
    project_id: 'prj_1',
    contract_id: 'ctr_dev_3',
    tranche_id: 'tra_dev_3_2',
    dev_id: 'usr_dev_3',
    amount_ht: 5700.0,
    tva_rate: 0,
    amount_ttc: 5700.0,
    status: 'PENDING',
    issue_date: '2026-08-30',
    due_date: '2026-09-15',
    items: [
      {
        id: 'pitem_6',
        description: 'Tranche contractuelle 2 (60%) - Solde Tunnel de Commande & Responsive QA',
        quantity: 1,
        unit_price: 5700,
        total: 5700.0,
      },
    ],
    notes: 'Tunnel de commande livré et intégré - Prêt pour exécution virement.',
  },
];
